### ISSUE TITLE
Error: Cannot find module 'rollup-plugin-node-globals'

### ISSUE THREAD

**Issue by mixersoft** [smichelotti/ionic2-google-maps-test#1]
I cloned your project and it works.  when I do an `npm list | grep rollup` I get

```
│ ├─┬ rollup@0.36.1
│ ├─┬ rollup-plugin-commonjs@5.0.4
│ ├── rollup-plugin-json@2.0.2
│ ├─┬ rollup-plugin-node-builtins@1.2.1
│ ├─┬ rollup-plugin-node-globals@1.0.9
│ ├─┬ rollup-plugin-node-resolve@2.0.0
│ ├─┬ rollup-pluginutils@1.5.2
```

I added the `rollup.config.js` script to my project, but when I tried to build I got an error: `[08:43:02]  Error: Cannot find module 'rollup-plugin-node-globals'`

In my existing ionic2 project (`ionic info` reports the same versions), I only see:

```
│ ├─┬ rollup@0.36.0
│ ├─┬ rollup-plugin-commonjs@5.0.4
│ ├─┬ rollup-plugin-node-resolve@2.0.0
│ ├─┬ rollup-pluginutils@1.5.2
```

How did you add the additional `rollup dependencies`?  `npm install` did not do the trick.

**Comment by mixersoft** [comment]
nevermind. I ran `npm install` a couple more times and maybe that fixed it because all the dependencies are there now.

**Comment by ChiKler** [comment]
I had the same issue, and ran the following commands to fix it;

```
npm install rollup-plugin-html2
npm i rollup-plugin-serve
```

**Comment by txiklerr** [comment]
I had the same issue, and ran the following commands to fix it;

```
npm install rollup-plugin-html2
npm install rollup-plugin-serve
```

I also had tried installing it globally out of pure desperation, but it didn't solve the problem at all. The culprits were those two plugins!
